/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginVerifyEmailRouteImport } from './routes/login/verify-email'
import { Route as LoginPasswordResetRouteImport } from './routes/login/password-reset'
import { Route as LoginPasswordRouteImport } from './routes/login/password'
import { Route as LoginPasskeyRouteImport } from './routes/login/passkey'
import { Route as LoginOneTimePasswordRouteImport } from './routes/login/one-time-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyEmailRoute = LoginVerifyEmailRouteImport.update({
  id: '/login/verify-email',
  path: '/login/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasswordResetRoute = LoginPasswordResetRouteImport.update({
  id: '/login/password-reset',
  path: '/login/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasswordRoute = LoginPasswordRouteImport.update({
  id: '/login/password',
  path: '/login/password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasskeyRoute = LoginPasskeyRouteImport.update({
  id: '/login/passkey',
  path: '/login/passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOneTimePasswordRoute = LoginOneTimePasswordRouteImport.update({
  id: '/login/one-time-password',
  path: '/login/one-time-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/one-time-password': typeof LoginOneTimePasswordRoute
  '/login/passkey': typeof LoginPasskeyRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/password-reset': typeof LoginPasswordResetRoute
  '/login/verify-email': typeof LoginVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/one-time-password': typeof LoginOneTimePasswordRoute
  '/login/passkey': typeof LoginPasskeyRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/password-reset': typeof LoginPasswordResetRoute
  '/login/verify-email': typeof LoginVerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/one-time-password': typeof LoginOneTimePasswordRoute
  '/login/passkey': typeof LoginPasskeyRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/password-reset': typeof LoginPasswordResetRoute
  '/login/verify-email': typeof LoginVerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/one-time-password'
    | '/login/passkey'
    | '/login/password'
    | '/login/password-reset'
    | '/login/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/one-time-password'
    | '/login/passkey'
    | '/login/password'
    | '/login/password-reset'
    | '/login/verify-email'
  id:
    | '__root__'
    | '/'
    | '/login/one-time-password'
    | '/login/passkey'
    | '/login/password'
    | '/login/password-reset'
    | '/login/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginOneTimePasswordRoute: typeof LoginOneTimePasswordRoute
  LoginPasskeyRoute: typeof LoginPasskeyRoute
  LoginPasswordRoute: typeof LoginPasswordRoute
  LoginPasswordResetRoute: typeof LoginPasswordResetRoute
  LoginVerifyEmailRoute: typeof LoginVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/verify-email': {
      id: '/login/verify-email'
      path: '/login/verify-email'
      fullPath: '/login/verify-email'
      preLoaderRoute: typeof LoginVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/password-reset': {
      id: '/login/password-reset'
      path: '/login/password-reset'
      fullPath: '/login/password-reset'
      preLoaderRoute: typeof LoginPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/password': {
      id: '/login/password'
      path: '/login/password'
      fullPath: '/login/password'
      preLoaderRoute: typeof LoginPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/passkey': {
      id: '/login/passkey'
      path: '/login/passkey'
      fullPath: '/login/passkey'
      preLoaderRoute: typeof LoginPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/one-time-password': {
      id: '/login/one-time-password'
      path: '/login/one-time-password'
      fullPath: '/login/one-time-password'
      preLoaderRoute: typeof LoginOneTimePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginOneTimePasswordRoute: LoginOneTimePasswordRoute,
  LoginPasskeyRoute: LoginPasskeyRoute,
  LoginPasswordRoute: LoginPasswordRoute,
  LoginPasswordResetRoute: LoginPasswordResetRoute,
  LoginVerifyEmailRoute: LoginVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
